mocked Js
Noderoid64/ISDBrowser pull request #18
Opened 2018-10-26 10:10 UTC by Oress

2018-10-26 12:11 UTC, Noderoid64 commented
1. Интерфейс и реализация мок класса не публичные
2. Название юнит тестов: метод_сценарий_ожидаемое поведение
3. Название классов в юнит тестах должно совпадать с названием тестируемого класса + test
4. .cache в .gitignore
5. eventPhase enum в отдельный файл
6. Что такое EspParser

2018-10-27 13:41 UTC, eugenezhornyak requested changes
Не используйте Console.WriteLine, а возвращайте стрингу. HoustonBrowser.JS/MockJS.cs

2018-10-27 13:52 UTC, Noderoid64 approved these changes

2018-10-27 13:57 UTC, eugenezhornyak approved these changes

2018-10-27 13:58 UTC, merged